### ISSUE TITLE
Mispositioned U+1C2C LEPCHA VOWEL SIGN E below U+1C37 LEPCHA SIGN NUKTA

### ISSUE THREAD

**Issue by dscorbett** [notofonts/lepcha#1]
### Font 
NotoSansLepcha-Regular.otf

### Where the fonts came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/4d7396a4fae475975b367e225f2e8f49292d8837/unhinted/otf/NotoSansLepcha/NotoSansLepcha-Regular.otf
Date: 2022-04-16

### Font version
Version 2.002

### Issue
U+1C2C LEPCHA VOWEL SIGN E should be positioned below U+1C37 LEPCHA SIGN NUKTA, but that only works in this font below single base letters. Below anything else, like U+25CC DOTTED CIRCLE or the cluster <U+1C00 LEPCHA LETTER KA, U+1C24 LEPCHA SUBJOINED LETTER YA>, the vowel sign overlaps the nukta.

### Character data
ᰀ᰷ᰤᰬ◌᰷ᰬ
U+1C00 LEPCHA LETTER KA
U+1C37 LEPCHA SIGN NUKTA
U+1C24 LEPCHA SUBJOINED LETTER YA
U+1C2C LEPCHA VOWEL SIGN E
U+25CC DOTTED CIRCLE
U+1C37 LEPCHA SIGN NUKTA
U+1C2C LEPCHA VOWEL SIGN E

### Screenshot
![ᰀ᰷ᰤᰬ◌᰷ᰬ](https://user-images.githubusercontent.com/1124347/163696127-d02fa01c-3f8c-4543-8daa-f7c297d04ba5.png)

**Comment by dscorbett** [comment]
The fix is incomplete in version 2.004. Some sequences have have fixed, like <U+1C13, U+1C37, U+1C25, U+1C2C>, because `uni1C13_1C25` is now a ligature glyph, but <U+1C00, U+1C37, U+1C25, U+1C2C> is still broken because `uni1C00_1C25` is a base glyph. The relevant 'ccmp' lookup only skips ligature glyphs.

**Comment by simoncozens** [comment]
Huh

**Comment by simoncozens** [comment]
Looks like my previous fix worked purely by chance. The anchors are there but mkmk is not happening; we're getting ligated marks instead.

**Comment by simoncozens** [comment]
I think I've got this now. The problem is that the cluster order goes below-base vowels, post-base things, and then below-base marks. One approach to this (which the font followed previously) is making the post-base glyphs into marks and filtering them out, but this makes mark attachment (particularly on OS X for some reason) not quite work. So we have to skip over post-base glyphs manually in the code, and there may be several. I don't know how many there can be in Lepcha. I've allowed for three, which allows for ra+ya+a vowel. Lepcha has a fairly simple vowel inventory; I don't think there can be more than one vowel together, so this should be enough.
